config/routes.rb
Loomio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  resources :group_requests, :only => :create
  match "/request_new_group", :to => "group_requests#new", :as => :request_new_group
  match "/group_request_confirmation", :to => "group_requests#confirmation", :as => :group_request_confirmation

  resources :groups, except: :index do
    post :add_members, on: :member
    get :add_subgroup, on: :member
    resources :motions#, name_prefix: "groups_"
    resources :discussions, only: :index
    get :request_membership, on: :member
    get :new_motion, :on => :member
    post :create_motion, :on => :member
    post :email_members, on: :member
    post :edit_description, :on => :member
    post :edit_privacy, on: :member
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post

  resources :motions do
    resources :votes
    put :edit_outcome, :on => :member
  end
  match "/motions/:id/close", :to => "motions#close_voting", :as => :close_motion_voting,
        :via => :post
  match "/motions/:id/open", :to => "motions#open_voting", :as => :open_motion_voting,
        :via => :post

  resources :discussions, only: [:index, :show, :create, :update] do
    post :edit_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
  end
  post "/discussion/preview_version/:version_id", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    post :mark_as_viewed, :on => :collection, :via => :post
  end

  resources :votes

  resources :memberships, except: [:new, :update, :show] do
    post :make_admin, on: :member
    post :remove_admin, on: :member
    post :approve_request, on: :member, as: :approve_request_for
    post :ignore_request, on: :member, as: :ignore_request_for
    post :cancel_request, on: :member, as: :cancel_request_for
  end

  resources :users do
    post :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
    post :reset_motion_read_log, on: :member
  end
  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments, only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end
  match "/settings", :to => "users#settings", :as => :user_settings

  # route logged in user to dashboard
  resources :dashboard, only: :show

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  match '/demo' => 'high_voltage/pages#show', :id => 'demo'
  match '/browser_not_supported' => 'high_voltage/pages#show', :id => 'browser_not_supported'
end

app/controllers/dashboard_controller.rb
class DashboardController < BaseController
  def show
    @discussion = Discussion.new
    @groups = GroupDecorator.decorate(current_user.root_groups)
  end
end

app/views/dashboard/_buttons.html.haml
%ul.button-list
  / %li= icon_button('#new-discussion', 'Start a discussion', '/assets/topic-18.png', 'start-new-discussion', true)
  %li= icon_button(request_new_group_path, 'Request new group', '/assets/group-18.png', 'request-new-group')
  %li= icon_button('#', 'See previous decisions', '/assets/pie-18.png', 'show-closed-motions')

app/views/dashboard/_group_link.html.haml
- group = GroupDecorator.decorate(group)
- if can? :show, group
  .group-link= group.link

app/views/dashboard/_group_summary.html.haml
%li
  %h3.clearfix.group-panel
    = link_to group.name, group_path(group)
    .parent-name= link_to "(#{group.parent.name})", group_path(group.parent) if group.parent
    .new-discussion-link
      %a{:href => '#new-discussion', 'data-toggle' => 'modal', 'data-group' => group.id, :class => 'btn btn-mini btn-grey'}
        .mini-icon.topic-icon
        Start a new discussion

  %ul.selector-list.bordered
    #discussions-with-motions
      - group.discussions_with_current_motion_not_voted_on(current_user).each do |discussion|
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: nil
      - group.discussions_with_current_motion_voted_on(current_user).each do |discussion|
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: nil
    - group.discussions.each do |discussion|
      - if ((discussion.never_read_by(current_user) || discussion.number_of_comments_since_last_looked(current_user) > 0) && (not discussion.current_motion))
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: nil
    / %li.new-discussion-link
    /   %a{:href => '#new-discussion', 'data-toggle' => 'modal', 'data-group' => group.id}
    /     Start a new discussion in this group

app/views/dashboard/_groups.html.haml
.sub-panel#groups
  %h3 Groups
  = icon_button(request_new_group_path, 'Request new group', '/assets/group-18.png', 'request-new-group')
  %ul#dashboard-groups-list
    - current_user.root_groups.each do |group|
      %li
        .group-link.clearfix
          .group-link-name= link_to group.name, group_path(group), :class => 'view_'+group.viewable_by.to_s
          .group-link-activity= render '/application/group_activity', user: current_user, group: group
        - if group.subgroups.size > 0
          - group.subgroups.each do |subgroup|
            - if (current_user && current_user.group_membership(subgroup))
              %li.sub-group
                .group-link.clearfix
                  .group-link-name= link_to subgroup.name, group_path(subgroup), :class => 'view_'+subgroup.viewable_by.to_s
                  .group-link-activity= render '/application/group_activity', user: current_user, group: subgroup

app/views/dashboard/show.html.haml
- if user_signed_in? && (not current_user.has_read_dashboard_notice?)
  - message = "Welcome to Loomio!\n This is the Home page, where you can see a list of the discussions "
  - message += "going on in all of your groups. To the right is a list of the groups you are a member of. "
  - message += "You can start a discussion on a new topic by clicking on the “Start a discussion” button.\n\n"
  - message += "If you have any questions or feedback we’d love to hear from you: "
  - message += "#{link_to "contact@loom.io", 'mailto:contact@loom.io', :target =>'_blank'}\n\n"
  =render '/application/helper_info', message: message, path: dismiss_dashboard_notice_for_user_path

- if @groups.present?
  -#=render '/application/loomio_process_flow'
  =render '/groups/title', group: nil
  .clearfix
    =render 'application/helper_bot'
    = icon_button('#new-discussion', 'Start a discussion', '/assets/topic-18.png', 'start-new-discussion', true)
  .row.main-content
    %section.span8
      %ul.selector-list.bordered
        #all-discussions-loading
          %li.selector-item.loading Loading...
        #discussions-with-motions
          - @discussions_with_current_motion_not_voted_on.each do |discussion|
            %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: nil
          - @discussions_with_current_motion_voted_on.each do |discussion|
            %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: nil
          .discussion-with-motion-divider.hidden
        - if current_user && current_user.discussions.count == 0
          %li.empty-list-message.hidden There are no discussions in any of your groups
      #user-discussions.hidden Loading...
    %section.span4
      =render 'groups'
      =render '/application/see_closed_motions'
    =render '/application/closed_motions', user: current_user, group: nil
    =render '/discussions/new', discussion: @discussion, user_groups: @groups
- else
  = link_to 'Create a group', new_group_path
  or wait until you are invited to one.