config/routes.rb
Loomio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  resources :group_requests, :only => :create
  match "/request_new_group", :to => "group_requests#new", :as => :request_new_group
  match "/group_request_confirmation", :to => "group_requests#confirmation", :as => :group_request_confirmation

  resources :groups, except: :index do
    post :add_members, on: :member
    get :add_subgroup, on: :member
    resources :motions#, name_prefix: "groups_"
    resources :discussions, only: :index
    get :request_membership, on: :member
    get :new_motion, :on => :member
    post :create_motion, :on => :member
    post :email_members, on: :member
    post :edit_description, :on => :member
    post :edit_privacy, on: :member
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post

  resources :motions do
    resources :votes
    put :edit_outcome, :on => :member
  end
  match "/motions/:id/close", :to => "motions#close_voting", :as => :close_motion_voting,
        :via => :post
  match "/motions/:id/open", :to => "motions#open_voting", :as => :open_motion_voting,
        :via => :post

  resources :discussions, only: [:index, :show, :create, :update] do
    post :edit_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
  end
  post "/discussion/preview_version/:version_id", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    post :mark_as_viewed, :on => :collection, :via => :post
  end

  resources :votes

  resources :memberships, except: [:new, :update, :show] do
    post :make_admin, on: :member
    post :remove_admin, on: :member
    post :approve_request, on: :member, as: :approve_request_for
    post :ignore_request, on: :member, as: :ignore_request_for
    post :cancel_request, on: :member, as: :cancel_request_for
  end

  resources :users do
    post :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
    post :reset_motion_read_log, on: :member
  end
  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments, only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end
  match "/settings", :to => "users#settings", :as => :user_settings

  # route logged in user to dashboard
  resources :dashboard, only: :show

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  match '/demo' => 'high_voltage/pages#show', :id => 'demo'
  match '/browser_not_supported' => 'high_voltage/pages#show', :id => 'browser_not_supported'
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  class AuthorValidator < ActiveModel::Validator
    def validate(record)
      unless (record.group.nil? || record.group.users.include?(record.author))
        record.errors[:author] << 'must be a member of the discussion group'
      end
    end
  end

  # Do we even need this?
  # validates_with AuthorValidator
  validates_presence_of :title, :group, :author
  validates :title, :length => { :maximum => 150 }

  acts_as_commentable
  has_paper_trail :only => [:description]

  belongs_to :group
  belongs_to :author, class_name: 'User'
  has_many :motions
  has_many :votes, through: :motions
  has_many :comments,  :as => :commentable
  has_many :users_with_comments, :through => :comments,
    :source => :user, :uniq => true
  has_many :events, :as => :eventable, :dependent => :destroy

  delegate :users, :to => :group, :prefix => :group
  delegate :full_name, :to => :group, :prefix => :group
  delegate :email, :to => :author, :prefix => :author

  attr_accessible :group_id, :group, :title, :description

  attr_accessor :comment, :notify_group_upon_creation

  after_create :populate_last_comment_at


  #
  # COMMENT METHODS
  #

  def can_be_commented_on_by?(user)
    group.users.include? user
  end

  def add_comment(user, comment)
    if can_be_commented_on_by? user
      comment = Comment.build_from self, user.id, comment
      comment.save
      comment
    end
  end

  #
  # MISC METHODS
  #

  def read_log_for(user)
    DiscussionReadLog.where('discussion_id = ? AND user_id = ?',
      id, user.id).first
  end

  def never_read_by(user)
    read_log_for(user).nil?
  end

  def number_of_comments_since_last_looked(user)
    if user
      last_viewed_at = last_looked_at_by(user)
      if last_viewed_at 
        return number_of_comments_since(last_viewed_at)
      end
    end
    comments.count
  end

  def last_looked_at_by(user)
    discussion_read_log = read_log_for(user)
    if discussion_read_log
      discussion_read_log.discussion_last_viewed_at
    end
  end

  def number_of_comments_since(time)
    comments.where('comments.created_at > ?', time).count
  end

  def has_activity_since_group_last_viewed?(user)
    membership = group.membership(user)
    last_viewed_at = last_looked_at_by(user)
    if membership
      return true if group.discussions
        .includes(:comments)
        .where('discussions.id = ? AND comments.user_id <> ? AND comments.created_at > ? AND comments.created_at > ?', id, user.id, membership.group_last_viewed_at, last_viewed_at)
        .count > 0
      return true if never_read_by(user) && (created_at > membership.group_last_viewed_at)
    end
    false
  end

  def current_motion_close_date
    current_motion.close_date
  end

  def current_motion
    motion = motions.where("phase = 'voting'").last if motions
    if motion
      motion.open_close_motion
      motion if motion.voting?
    end
  end

  def closed_motion(motion)
    if motion
      motions.find(motion)
    else
      motions.where("phase = 'closed'").order("close_date desc").first
    end
  end

  def history
    (comments + votes + motions).sort!{ |a,b| b.created_at <=> a.created_at }
  end

  def latest_history_time
    if history.count > 0
      history.first.created_at
    else
      created_at
    end
  end

  def participants
    other_participants = []
    # Include discussion author
    unless users_with_comments.find_by_id(author.id)
      other_participants << author
    end
    # Include motion authors
    motions.each do |motion|
      unless users_with_comments.find_by_id(motion.author.id)
        other_participants << motion.author
      end
    end
    users_with_comments.all + other_participants.uniq
  end

  def latest_comment_time
    if comments.count > 0
      comments.order('created_at DESC').first.created_at
    else
      created_at
    end
  end

  private

  def populate_last_comment_at
    self.last_comment_at = created_at
    save
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < GroupBaseController
  load_and_authorize_resource :except => [:show, :create, :index]
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :check_group_read_permissions, :only => :show

  def new
    @group = GroupDecorator.new(Group.find(params[:discussion][:group_id]))
    @discussion = Discussion.new(group: @group)
  end

  def create
    @discussion = current_user.authored_discussions.new(params[:discussion])
    authorize! :create, @discussion
    if @discussion.save
      @discussion.add_comment(current_user, params[:discussion][:comment])
      if params[:discussion][:notify_group_upon_creation].to_i > 0
        DiscussionMailer.spam_new_discussion_created(@discussion)
      end
      Event.new_discussion!(@discussion)
      flash[:success] = "Discussion sucessfully created."
      redirect_to @discussion
    else
      render action: :new
      flash[:error] = "Discussion could not be created."
    end
  end

  def index
    if params[:group_id].present?
      @group = Group.find(params[:group_id])
      if cannot? :show, @group
        head 401
      else
        @discussions = @group.discussions_sorted(current_user).page(params[:page]).per(10)
        render :layout => false if request.xhr?
      end
    else
      authenticate_user!
      @discussions = current_user.discussions_sorted.page(params[:page]).per(10)
      render :layout => false if request.xhr?
    end
  end

  def show
    @discussion = Discussion.find(params[:id])
    @group = GroupDecorator.new(@discussion.group)
    @current_motion = @discussion.current_motion
    @vote = Vote.new
    @history = @discussion.history
    if (not params[:proposal])
      if @current_motion
        @unique_votes = Vote.unique_votes(@current_motion)
        @votes_for_graph = @current_motion.votes_graph_ready
        @user_already_voted = @current_motion.user_has_voted?(current_user)
      end
    else
      @selected_motion = @discussion.closed_motion(params[:proposal])
      @user_already_voted = @selected_motion.user_has_voted?(current_user)
      @votes_for_graph = @selected_motion.votes_graph_ready
    end

    if current_user
      current_user.update_motion_read_log(@current_motion) if @current_motion
      current_user.update_discussion_read_log(@discussion)
    end
  end

  def add_comment
    comment = resource.add_comment(current_user, params[:comment])
    if comment.valid?
      Event.new_comment!(comment)
    else
      flash[:error] = "Comment could not be created."
    end
    redirect_to discussion_path(resource.id)
  end

  def new_proposal
    @motion = Motion.new
    discussion = Discussion.find(params[:id])
    @motion.discussion = discussion
    @group = GroupDecorator.new(discussion.group)
    render 'motions/new'
  end

  def edit_description
    discussion = Discussion.find(params[:id])
    @description = params[:description]
    discussion.description = @description
    discussion.save!
  end

  def edit_title
    discussion = Discussion.find(params[:id])
    discussion.title = params[:title]
    discussion.save!
  end

  def show_description_history
    @discussion = Discussion.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def preview_version
    version = Version.find(params[:version_id])
    @discussion = version.reify
    respond_to do |format|
      format.js { render :action => 'show_description_history' }
    end    
  end

  def update_version
    @version = Version.find(params[:version_id])
    @version.reify.save!
    @discussion = @version.item
    respond_to do |format|
      format.js { render :nothing => true}
    end     
  end

  private

  def group
    @group ||= find_group
  end

  def find_group
    if (params[:id] && (params[:id] != "new"))
      Discussion.find(params[:id]).group
    elsif params[:discussion][:group_id]
      Group.find(params[:discussion][:group_id])
    end
  end

  def mock_discussion

  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def discussion_activity_count_for(discussion, user)
    discussion.number_of_comments_since_last_looked(user)
  end

  def enabled_icon_class_for(discussion, user)
    if discussion_activity_count_for(discussion, user) > 0
      "enabled-icon"
    else
      "disabled-icon"
    end
  end

  def css_class_unread_discussion_activity_for(page_group, discussion, user)
    css_class = "discussion-preview"
    css_class += " showing-group" if (not discussion.group.parent.nil?) && (page_group && (page_group.parent.nil?))
    css_class += " unread" if discussion.number_of_comments_since_last_looked(user) > 0
    css_class
  end

  def css_class_unread_group_activity_for(discussion, user)
    css_class = "group-activity-indicator"
    css_class += " unread-group-activity" if user_signed_in? && params[:group_id] && discussion.has_activity_since_group_last_viewed?(user)
    css_class
  end

  def css_class_for_close_date(motion)
    css_class = "popover-close-date label"

    if motion.close_date
      hours_left = (((Time.now - motion.close_date) / 60) / 60) * -1
      css_class += " color-urgent" if hours_left < 30
      css_class += " color-warning" if (hours_left >= 3) && (hours_left <= 24)
      css_class += " color-ok" if hours_left > 24
    end
    css_class
  end
 
  def render_position_message(vote)
    message = vote.position_to_s
    if vote.previous_vote
      message += " (previously " + vote.previous_vote.position_to_s + ")"
    end
    message += vote.statement.blank? ? "." : ":"
    message
  end
end

app/views/discussions/_add_comment.html.haml
- if can? :add_comment, discussion
  = form_tag add_comment_discussion_path(discussion), id: "new-comment-form" do
    .medium-user-avatar.avatar-canvas
      - if current_user.avatar_url
        = image_tag current_user.avatar_url(:medium)
      - else
        %span.medium-user-initials.initials-decoration= current_user.avatar_initials
    = text_area_tag 'comment', "", id: 'new-comment', placeholder: "Say something..."
    = submit_tag "Post comment", class: "btn btn-small btn-grey submit", id: 'post-new-comment', :data => {:disable_with => "Post comment"}

app/views/discussions/_description_history.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h2 Revision history
.modal-header
  .user-profile-fields
    %h4 User Profile Fields
    %p= "Edited about #{time_ago_in_words(@discussion.updated_at)} ago by #{@discussion.originator}"
  .revision-version
    %h4 Version
    %p
      -if @discussion.previous_version.nil?
        =link_to "Prev", "#", :method => :post, :class => "disabled",  :remote => true
      -else
        =link_to "Prev", preview_version_discussion_path(@discussion.previous_version.version), :method => :post, :remote => true
      =" | "
      -if @discussion.next_version.nil?
        =link_to "Next", "#", :method => :post, :class => "disabled", :remote => true
      -else
        =link_to "Next", preview_version_discussion_path(@discussion.next_version.version), :method => :post, :remote => true
.modal-body
  %p= @discussion.description
.modal-footer
  = link_to "Cancel", "#", "data-dismiss" => "modal", class: "btn btn-small btn-grey"
  =button_to "Go back to this version", update_description_discussion_path(@discussion), "data-dismiss" => "modal", :method => :post, :class => "btn btn-info", :data => { :disable_with => "Applying changes..." }

app/views/discussions/_discussion_preview.html.haml
.clearfix
  %span{ class: css_class_unread_group_activity_for(discussion, current_user)}
  %div{ class: css_class_unread_discussion_activity_for(this_group, discussion, current_user), id: "discussion-preview-#{discussion.id}" }
    %a.selector-discussion-link{ href: discussion_path(discussion) }
      - if user_signed_in? && discussion.current_motion
        .vote-icon
          - if current_user.group_membership(this_group) || this_group.nil?
            = render "motions/display_icons", position: current_user.position(discussion.current_motion)
      .discussion-title
        = truncate(discussion.title, :length => 60, :separator => ' ')
        .group-name= DiscussionDecorator.new(discussion).display_group_name(this_group)
 
      .large-icon.discussion-icon.activity-icon{ class: enabled_icon_class_for(discussion, current_user) }
        - discussion_activity = discussion_activity_count_for(discussion, current_user)
        - if discussion_activity > 0
          %span.activity-count.label.label-info
            = discussion_activity
      .discussion-date-info
        -if discussion.current_motion
          - if discussion.current_motion_close_date
            .proposal-close-date= "#{time_ago_in_words(discussion.current_motion_close_date)} until close"
        - else
          .latest-comment-time= "#{time_ago_in_words(discussion.latest_comment_time)} ago"
    - if discussion.current_motion
      - motion_activity = motion_activity_count_for(discussion.current_motion, current_user)
      - pop_over_title = render "discussions/graph_preview_pop_over_title", motion: discussion.current_motion
      - pop_over_body = render "discussions/graph_preview_pop_over", motion: discussion.current_motion, user: current_user, motion_activity: motion_activity
      .selector-pie-link{ "data-title" => pop_over_title, "data-content" => pop_over_body }
        .pie{:id => "graph_#{discussion.current_motion.id}"}
          - if discussion.current_motion.voting? && motion_activity > 0
            %span.activity-count.label.label-info
              = motion_activity
          - if user_signed_in?
            = button_to '', reset_motion_read_log_user_path(current_user, :motion => discussion.current_motion, :motion_activity => motion_activity), :remote => true, :class =>  "preview-pie-button"
    - else
      .large-icon.pie-icon.activity-icon

- if discussion.current_motion
  :coffeescript
    $ ->
      # Display vote graph
      make_the_graph = ->
        @pie_graph_view = new Loomio.Views.Utils.GraphView
          el: '.pie'
          id_string: "graph_#{discussion.current_motion.id}"
          legend: false
          data: #{discussion.current_motion.votes_graph_ready.to_json.html_safe}
          type: 'pie'
          tooltip_selector: '#tooltip'
          diameter: 25
          padding: 1
          gap: 1
          shadow: 0.75

      # IE8 FIX - for some reason we have to load the graph after everything else.
      # Otherwise, the graph doesn't display in IE8.
      #
      # Ideally, we'd like to be able to delete this line:
      $(window).load(make_the_graph)

app/views/discussions/_form.html.haml
= form_for(discussion) do |f|
  .modal-body
    .row
      .span5
        = f.hidden_field :group_id, id: 'group_id'
        .control-group
          = f.label :title, "Title", { class: "control-label", for: "validate-presence"}
          .presence-error-message Please fill in a title
          = f.text_field :title, :placeholder => "What is the topic you'd like to discuss?", class: "validate-presence inputError limit-150"
          .character-counter
        .control-group
          = f.label :description, "Context", { class: "control-label", for: "validate-presence"}
          .presence-error-message Please fill in some info on the discussion
          = f.text_area :description, :placeholder => "This information will appear at the top of the discussion page. Introduce the topic and give enough context for your group to have a well-informed discussion."
        .control-group
          = f.check_box :notify_group_upon_creation
          = f.label :notify_group_upon_creation,
            "Email group members to announce the new discussion.", class: "checkbox-label"
  .modal-footer
    = link_to "Cancel", "#", "data-dismiss" => "modal", class: "btn btn-small btn-grey"
    = f.submit "Start", class: "btn btn-info run-validations", id: "discussion-submit", :data => { :disable_with => "Starting" }

app/views/discussions/_graph_preview_pop_over.html.haml
- if user_signed_in?
  %span.popover-current-position
    = "Your position"
    .popover-current-position-icon= render "motions/display_icons", position: user.get_position_for(motion)

.popover-engagement
  = "Engagement #{motion.percent_voted}%"

- if user_signed_in?
  - new_vote_count = motion.number_of_votes_since_last_looked(user)
  - if new_vote_count > 0
    .popover-header
      New activity
    %ul.popover-activity-list
      - motion.votes.order('created_at DESC')[(0..new_vote_count - 1)].each do |vote|
        %li.popover-item
          = render "discussions/graph_preview_pop_over_votes", vote: vote, motion: motion

app/views/discussions/_graph_preview_pop_over_title.html.haml
%span.popover-header-title
  = "Proposal" 
%span{class: css_class_for_close_date(motion)}
  - if motion.close_date
    = "#{time_ago_in_words(motion.close_date)} until close"
.popover-motion-name
  = motion.name

app/views/discussions/_graph_preview_pop_over_votes.html.haml
.medium-user-avatar.avatar-canvas#header-user-image
  - if vote.user.avatar_url.nil?
    %span.medium-user-initials.initials-decoration= vote.user.avatar_initials
  - else
    = image_tag vote.user.avatar_url("medium")
= render "motions/display_icons", position: vote.position
= vote.statement
.vote-time
  = time_ago_in_words(vote.created_at) + " ago"

app/views/discussions/_history.html.haml
%ul.history-list
  .divider
  - if history.count == 0
    %li.selector-item.empty-list-message.history-item
      There aren't any messages in this discussion yet.
  - else
    - history.each do |message|
      - if message.is_a?(Comment)
        %li.history-item~ render message
      - if message.is_a?(Vote)
        %li.history-item
          .comment-container
            .comment.position
              .position-icon
                = render partial: "motions/display_icons", locals: { position: message.position }
              %span.comment-username 
                =link_to message.user_name, "#", "title" => message.user_name,
                  "data-content" => "#{render 'users/name_popover', user: message.user, group: discussion.group}", 
                  class: "user-name-with-popover"
              %span.comment-label= render_position_message message
              - if message.statement.present?
                %span.position-message.word-break= "\"#{message.statement}\""
              .comment-time
                = time_ago_in_words(message.created_at) + " ago"
      - if message.is_a?(Motion)
        %li.history-item
          - classes = "comment proposal"
          - classes += " current" if (message == discussion.current_motion)
          %div{class: classes}
            .comment-container
              .proposal-icon
              %span.comment-username 
                =link_to message.author_name, "#", "title" => message.author_name,
                  "data-content" => "#{render 'users/name_popover', user: message.author, group: discussion.group}", 
                  class: "user-name-with-popover"
              %span.comment-label created a proposal:
              %span.proposal-text.word-break= " \"#{message.name}\""
              .comment-time
                = time_ago_in_words(message.created_at) + " ago"

app/views/discussions/_new.html.haml
#new-discussion.modal.hidden
  .modal-header
    %button.close{"data-dismiss" => "modal"}×
    %h2 Start a discussion
  = render "/discussions/form", :discussion => discussion

app/views/discussions/_new_loomio.html.haml
#new-loomio.modal.hidden
  .modal-header
    %button.close{"data-dismiss" => "modal"}×
    %h2 Start a new loomio
  = form_for discussion do |f|
    .modal-body
      .row
        .span10
          - if params[:controller] == 'dashboard'
            .row
              .span5
                .control-group
                  = f.label :group_id, "Group", {class: "control-label", for: "validate-presence"}
                  .presence-error-message.hidden Please select a group for this loomio
                  = f.collection_select :group_id, user_groups, :id, :name, {:prompt => "Select group"}, {:class => 'validate-presence'}
              .span5
                .helper-text.align-with-input
                  %p Select the group you want to start this Loomio in
          - else
            = f.hidden_field :group_id
          .row
            .span5
              .control-group
                = f.label :title, "Title", {class: "control-label", for: "validate-presence"}
                .presence-error-message Please fill in a title for this loomio
                = f.text_field :title, class: "validate-presence inputError limit-150"
                .character-counter
            .span5
              .helper-text.align-with-input
                %p The topic you wish to discuss, e.g. “...”
          = f.label :description, "Description"
          .row
            .span5
              = f.text_area :description
            .span5
              .helper-text
                %p Give some background, etc...
          = f.check_box :notify_group_upon_creation
          = f.label :notify_group_upon_creation,
            "Send email notification to group members that this loomio has been created",
            class: "checkbox-label"
    .modal-footer
      = f.submit "Start loomio", class: "btn btn-info run-validations"
      = link_to "Cancel", "#", "data-dismiss" => "modal", class: "btn btn-small"

app/views/discussions/edit_title.js.erb
var title = $("#discussion-input").val()
$("#discussion-title").html(title)
$("#discussion-title").removeClass('hidden')
$("#edit-discussion-title").addClass('hidden')

app/views/discussions/index.html.haml
%ul.selector-list
  #discussion-list
    - if @discussions.exists?
      - @discussions.each do |discussion|
        %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: @group
  #discussions-loading
    %li.selector-item.loading Loading...
= paginate @discussions, :window => 3, :remote => :true
- current_user.update_group_last_viewed_at(@group) if current_user && params[:group_id]

app/views/discussions/show.html.haml
- set_title @group.name, @discussion.title, @group.parent
- if current_user && (not current_user.has_read_discussion_notice?)
  - message = "The discussion topic is at the top of the page, followed by background information and context.\n\n"
  - message += "Discussion is on the left: to add a comment, write in the text box and click ‘Post comment’.\n\n"
  - message += "Decisions are on the right. If you think the group is ready to make a decision, "
  - message += "you can make a proposal for the group to consider. If someone has already made a proposal, "
  - message += "you can see how the group feels on the pie graph, and state your position underneath.\n\n"
  =render '/application/helper_info', message: message, path: dismiss_discussion_notice_for_user_path

=render '/groups/title', group: @group
=render 'application/helper_bot' 
.row
  .span12
    .selector-panel
      = render 'title', discussion: @discussion
      #discussion-panel-content
        #discussion-context
          .row
            .span8
              =render '/application/description', model: @discussion, model_name: "discussion"
            .span3.right-context
              .helper-text.discussion-description-helper-text.hidden
                %p Use this panel to give enough context for your group to have a well-informed discussion. As the discussion progresses, anyone can add information to make it easy for new people to get up to speed.
              .discussion-additional-info
                = "Started #{time_ago_in_words(@discussion.created_at)} ago"
                .started-by
                  = "By #{@discussion.originator}"
                  =link_to @discussion.author.name, "#", "title" => @discussion.author.name,
                    "data-content" => "#{render 'users/name_popover', user: @discussion.author, group: @discussion.group}",
                    class: "user-name-with-popover"
                .last-edited-by
                  = "By "
                .see-revision-history
                  =link_to "See revision history", show_description_history_discussion_path(@discussion), :method => :post, :class => "see-description-history", :remote => true
        #description-revision-history.modal.hidden
        .row
          .span6#content-history
            .large-icon.discussion-icon.enabled-icon
            %h2.header-text Discussion
            #content-history-body
              = render 'add_comment', discussion: @discussion
              = render 'history', discussion: @discussion, history: @discussion.history

          .span6#content-proposal
            .large-icon.decision-icon
            %h2.header-text Current decision
            .content-proposal-body
              %ul.selector-list
                - if @current_motion
                  - if (not @selected_motion) && (can? :close_voting, @current_motion)
                    %li= link_to "Close proposal", close_motion_voting_path(@current_motion),
                      :data => {confirm: "Are you sure you want to close this motion?"}, method: :post, class: 'btn btn-small proposal-btn', id: 'close-voting'
                  - if @selected_motion && (@selected_motion != @current_motion)
                    %li.selector-item.current-proposal
                      = render '/motions/motion_preview', motion: @current_motion, this_group: @group
                  - else
                    %li.selector-item.current-proposal
                      = render @current_motion, unique_votes: @unique_votes
                - else
                  - if can? :create, Motion.new(discussion_id: @discussion.id)
                    = link_to "Create new proposal", new_proposal_discussion_path(@discussion.id), class: 'btn btn-small proposal-btn', id: 'new-proposal'
                  %li.selector-item.empty-list-message= "There is not currently an open proposal under discussion"

            - if @discussion.motions.where("phase = 'closed'").count > 0
              #previous-proposals
                .clearfix
                  .large-icon.decision-icon
                  %h2.header-text Previous decisions

                .content-proposal-body
                  %ul.selector-list
                    - @discussion.motions.order("close_date desc").each do |closed_motion|
                      - if closed_motion.closed?
                        - if closed_motion == @selected_motion
                          %li.selector-item= render @selected_motion, unique_votes: @unique_votes, this_group: @group
                        - else
                          %li.selector-item= render '/motions/motion_preview', motion: closed_motion, this_group: @group

app/views/discussions/show_description_history.js.erb
var modal = $("#description-revision-history")

if(modal.is(":hidden")){
  modal.modal
  modal.modal('show')
}

modal.html("<%= escape_javascript(render 'description_history', model: @discussion, model_name: 'discussion')%>")
modal.find("a.disabled").bind('click', false)