config/routes.rb
Loomio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  resources :group_requests, :only => :create
  match "/request_new_group", :to => "group_requests#new", :as => :request_new_group
  match "/group_request_confirmation", :to => "group_requests#confirmation", :as => :group_request_confirmation

  resources :groups, except: :index do
    post :add_members, on: :member
    get :add_subgroup, on: :member
    resources :motions#, name_prefix: "groups_"
    resources :discussions, only: :index
    get :request_membership, on: :member
    get :new_motion, :on => :member
    post :create_motion, :on => :member
    post :email_members, on: :member
    post :edit_description, :on => :member
    post :edit_privacy, on: :member
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post

  resources :motions do
    resources :votes
    put :edit_outcome, :on => :member
  end
  match "/motions/:id/close", :to => "motions#close_voting", :as => :close_motion_voting,
        :via => :post
  match "/motions/:id/open", :to => "motions#open_voting", :as => :open_motion_voting,
        :via => :post

  resources :discussions, only: [:index, :show, :create, :update] do
    post :edit_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
  end
  post "/discussion/preview_version/:version_id", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    post :mark_as_viewed, :on => :collection, :via => :post
  end

  resources :votes

  resources :memberships, except: [:new, :update, :show] do
    post :make_admin, on: :member
    post :remove_admin, on: :member
    post :approve_request, on: :member, as: :approve_request_for
    post :ignore_request, on: :member, as: :ignore_request_for
    post :cancel_request, on: :member, as: :cancel_request_for
  end

  resources :users do
    post :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
    post :reset_motion_read_log, on: :member
  end
  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments, only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end
  match "/settings", :to => "users#settings", :as => :user_settings

  # route logged in user to dashboard
  resources :dashboard, only: :show

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  match '/demo' => 'high_voltage/pages#show', :id => 'demo'
  match '/browser_not_supported' => 'high_voltage/pages#show', :id => 'browser_not_supported'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates_presence_of :user, :event
  validates_uniqueness_of :user_id, :scope => :event_id

  delegate :kind, :to => :event, :prefix => :event
  delegate :eventable, :to => :event

  attr_accessible :user, :event

  default_scope order("id DESC")

  scope :unviewed, where("viewed_at IS NULL")

  def method_missing method_name, *args
    name = method_name.to_s
    if name =~ /^(discussion|comment|motion|vote|membership|comment_vote|user_mentioned)$/
      event.eventable if event.eventable_type == name.camelize
    else
      super
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < BaseController
  def index
    @notifications = []
    if user_signed_in?
      @notifications = current_user.notifications.page(params[:page]).per(15)
    end
  end

  def mark_as_viewed
    current_user.mark_notifications_as_viewed! params[:latest_viewed]
    head :ok
  end
end

app/views/notifications/_notification.html.haml
- begin
  - if notification.event_kind == "new_discussion"
    - discussion = notification.discussion
    - user = discussion.author
    - action_text = "started a new discussion"
    - title_text = discussion.title
    - group_name = discussion.group_full_name
    - href = discussion_path(discussion)

  - elsif notification.event_kind == "new_comment"
    - comment = notification.comment
    - user = comment.user
    - action_text = "commented on the discussion"
    - title_text = comment.discussion.title
    - group_name = comment.group_full_name
    - href = discussion_path(comment.discussion)

  - elsif notification.event_kind == "new_motion"
    - motion = notification.motion
    - user = motion.author
    - action_text = "created a new proposal"
    - title_text = motion.name
    - group_name = motion.group_full_name
    - href = discussion_path(motion.discussion)

  - elsif notification.event_kind == "motion_closed"
    - motion = notification.motion
    - user = notification.event.user
    - group_name = motion.group_full_name
    - title_text = motion.name
    - href = discussion_path(motion.discussion, proposal: motion)
    - action_text = "closed the proposal"

  - elsif notification.event_kind == "new_vote"
    - vote = notification.vote
    - user = vote.user
    - action_text = "#{Vote::POSITION_VERBS[vote.position]} on the proposal"
    - title_text = vote.motion_name
    - group_name = vote.group_full_name
    - href = discussion_path(vote.discussion, :proposal => vote.motion.id)

  - elsif notification.event_kind == "motion_blocked"
    - vote = notification.vote
    - user = vote.user
    - action_text = "blocked the proposal"
    - title_text = vote.motion_name
    - group_name = vote.group_full_name
    - href = discussion_path(vote.discussion, :proposal => vote.motion.id)

  - elsif notification.event_kind == "membership_requested"
    - membership = notification.membership
    - user = membership.user
    - action_text = "requested membership to"
    - title_text = membership.group_full_name
    - group_name = membership.group_full_name
    - href = group_path(membership.group)

  - elsif notification.event_kind == "user_added_to_group"
    - membership = notification.membership
    - user = membership.inviter
    - action_text = "added you to the group"
    - title_text = membership.group_full_name
    - group_name = membership.group_full_name
    - href = group_path(membership.group)

  - elsif notification.event_kind == "comment_liked"
    - comment_vote = notification.comment_vote
    - user = comment_vote.user
    - action_text = "liked your comment in the discussion"
    - title_text = comment_vote.discussion_title
    - group_name = comment_vote.group_full_name
    - href = (discussion_path(comment_vote.discussion))+"#comment-#{comment_vote.comment_id}"

  - elsif notification.event_kind == "mention"
    - comment = notification.comment
    - user = comment.user
    - action_text = "mentioned you in a comment in"
    - title_text = comment.discussion_title
    - group_name = comment.group_full_name
    - href = (discussion_path(comment.discussion))+"#comment-#{comment.id}"

  - date = time_ago_in_words(notification.created_at)
  - class_name = notification.viewed_at.nil? ? " unread" : ""
  - if user
    - avatar_url = user.avatar_url(:medium)
    - avatar_initials = user.avatar_initials

  %li.selector-item{:class => "notification-item#{class_name}" }
    %a{:href => href }
      %span.medium-user-avatar.avatar-canvas
        - if avatar_url.present?
          = image_tag avatar_url
        - else
          %span.medium-user-initials.initials-decoration
            = avatar_initials
      %span.notification-content
        %span.bold-name= user.name
        = " #{action_text} "
        - if title_text
          %span.bold-name= truncate(title_text, :length => 80, :omission => '...')
        %span.notification-item-footer
          = "#{date} ago · #{group_name}"

- rescue => exception
  - logger.error("NOTIFICATION ERROR: It looks like something got deleted without it's corresponding events/notifications being deleted as well. notification_id: #{notification.id}")
  -# TODO: Once we sort out a better deleting system for groups (https://trello.com/c/ll1na7KL) we should change this to a proper exception notification
  -#       so we know if there are any lingering notifications hanging around that shouldn't exist
  -#- ExceptionNotifier::Notifier.exception_notification(request.env, exception,
    -#:data => {:notification_id => notification.id, :message => "This error most likely means that something got deleted without it's corresponding events/notifications being deleted as well notification_id: #{notification.id}").deliver


          

app/views/notifications/index.html.haml
.row
  .span8.offset2
    .selector-panel
      .clearfix
        %h1.panel-header Notifications
      %ul.selector-list
        - @notifications.each do |notification|
          = render notification
      = paginate @notifications, :window => 3

app/views/notifications/index.js.erb
$("#notifications-count").html("0 Notifications")
document.title = "Loomio"