config/routes.rb
Loomio::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  resources :group_requests, :only => :create
  match "/request_new_group", :to => "group_requests#new", :as => :request_new_group
  match "/group_request_confirmation", :to => "group_requests#confirmation", :as => :group_request_confirmation

  resources :groups, except: :index do
    post :add_members, on: :member
    get :add_subgroup, on: :member
    resources :motions#, name_prefix: "groups_"
    resources :discussions, only: :index
    get :request_membership, on: :member
    get :new_motion, :on => :member
    post :create_motion, :on => :member
    post :email_members, on: :member
    post :edit_description, :on => :member
    post :edit_privacy, on: :member
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post

  resources :motions do
    resources :votes
    put :edit_outcome, :on => :member
  end
  match "/motions/:id/close", :to => "motions#close_voting", :as => :close_motion_voting,
        :via => :post
  match "/motions/:id/open", :to => "motions#open_voting", :as => :open_motion_voting,
        :via => :post

  resources :discussions, only: [:index, :show, :create, :update] do
    post :edit_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
  end
  post "/discussion/preview_version/:version_id", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    post :mark_as_viewed, :on => :collection, :via => :post
  end

  resources :votes

  resources :memberships, except: [:new, :update, :show] do
    post :make_admin, on: :member
    post :remove_admin, on: :member
    post :approve_request, on: :member, as: :approve_request_for
    post :ignore_request, on: :member, as: :ignore_request_for
    post :cancel_request, on: :member, as: :cancel_request_for
  end

  resources :users do
    post :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
    post :reset_motion_read_log, on: :member
  end
  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments, only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end
  match "/settings", :to => "users#settings", :as => :user_settings

  # route logged in user to dashboard
  resources :dashboard, only: :show

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
  match '/demo' => 'high_voltage/pages#show', :id => 'demo'
  match '/browser_not_supported' => 'high_voltage/pages#show', :id => 'browser_not_supported'
end

app/models/group.rb
class Group < ActiveRecord::Base
  PERMISSION_CATEGORIES = [:everyone, :members, :admins, :parent_group_members]

  attr_accessible :name, :viewable_by, :parent_id, :parent
  attr_accessible :members_invitable_by, :email_new_motion, :description

  validates_presence_of :name
  validates_inclusion_of :viewable_by, in: PERMISSION_CATEGORIES
  validates_inclusion_of :members_invitable_by, in: PERMISSION_CATEGORIES
  validate :limit_inheritance

  validates_length_of :name, :maximum=>250
  validates :description, :length => { :maximum => 250 }

  after_initialize :set_defaults
  after_create :create_welcome_loomio
  after_create :add_creator_as_admin

  default_scope where(:archived_at => nil)

  has_many :memberships,
    :conditions => {:access_level => Membership::MEMBER_ACCESS_LEVELS},
    :dependent => :destroy,
    :extend => GroupMemberships,
    :include => :user,
    :order => "LOWER(users.name)"
  has_many :membership_requests,
    :conditions => {:access_level => 'request'},
    :class_name => 'Membership',
    :dependent => :destroy
  has_many :admin_memberships,
    :conditions => {:access_level => 'admin'},
    :class_name => 'Membership',
    :dependent => :destroy
  has_many :users, :through => :memberships # TODO: rename to members
  has_many :requested_users, :through => :membership_requests, source: :user
  has_many :admins, through: :admin_memberships, source: :user
  has_many :discussions, :dependent => :destroy
  has_many :motions, :through => :discussions
  has_many :motions_in_voting_phase,
           :through => :discussions,
           :source => :motions,
           :conditions => { phase: 'voting' },
           :order => 'close_date'
  has_many :motions_closed,
           :through => :discussions,
           :source => :motions,
           :conditions => { phase: 'closed' },
           :order => 'close_date DESC'

  belongs_to :parent, :class_name => "Group"
  has_many :subgroups, :class_name => "Group", :foreign_key => 'parent_id'

  belongs_to :creator,  :class_name => "User"

  delegate :include?, :to => :users, :prefix => true
  delegate :users, :to => :parent, :prefix => true
  delegate :name, :to => :parent, :prefix => true
  delegate :email, :to => :creator, :prefix => true

  #
  # ACCESSOR METHODS
  #

  def beta_features
    if parent && (parent.beta_features == true)
      true
    else
      self[:beta_features]
    end
  end

  def beta_features?
    beta_features
  end

  def viewable_by
    value = read_attribute(:viewable_by)
    value.to_sym if value.present?
  end

  def viewable_by=(value)
    write_attribute(:viewable_by, value.to_s)
  end

  def members_invitable_by
    value = read_attribute(:members_invitable_by)
    value.to_sym if value.present?
  end

  def members_invitable_by=(value)
    write_attribute(:members_invitable_by, value.to_s)
  end

  def full_name(separator= " - ")
    if parent
      parent_name + separator + name
    else
      name
    end
  end

  def root_name
    if parent
      parent_name
    else
      name
    end
  end

  def users_sorted
    users.order('lower(name)').all
  end

  def admin_email
    if admins.exists?
      admins.first.email
    elsif creator
      creator.email
    else
      "noreply@loom.io"
    end
  end

  #
  # ACTIVITY METHODS
  #
  #

  def activity_since_last_viewed?(user)
    membership = membership(user)
    if membership
      new_comments_since_last_looked_at_group = discussions
        .includes(:comments)
        .where('comments.user_id <> ? AND comments.created_at > ?' , user.id, membership.group_last_viewed_at)
        .count > 0
      new_comments_since_last_looked_at_discussions = discussions
        .joins('INNER JOIN discussion_read_logs ON discussions.id = discussion_read_logs.discussion_id')
        .where('discussion_read_logs.user_id = ? AND discussions.last_comment_at > discussion_read_logs.discussion_last_viewed_at',  user.id)
        .count > 0
      unread_comments = new_comments_since_last_looked_at_group &&
                        new_comments_since_last_looked_at_discussions

      # TODO: Refactor this to an active record query and write tests for it
      unread_new_discussions = Discussion.find_by_sql(["
        (SELECT discussions.id FROM discussions WHERE group_id = ? AND discussions.created_at > ?)
        EXCEPT
        (SELECT discussions.id FROM discussions
         INNER JOIN discussion_read_logs ON discussions.id = discussion_read_logs.discussion_id
         WHERE discussions.group_id = ? AND discussion_read_logs.user_id = ?);",
        id, membership.group_last_viewed_at, id, user.id])

      return true if unread_comments || unread_new_discussions.present?
    end
    false
  end

  #
  # MEMBERSHIP METHODS
  #

  def membership(user)
    memberships.where("group_id = ? AND user_id = ?", id, user.id).first
  end

  def add_request!(user)
    unless requested_users_include?(user) || users.exists?(user)
      if parent.nil? || user.group_membership(parent)
        membership = memberships.build_for_user(user, access_level: 'request')
        membership.save!
        GroupMailer.new_membership_request(membership).deliver
        reload
        membership
      end
    end
  end

  def add_member!(user, inviter=nil)
    unless users.exists?(user)
      unless membership = requested_users_include?(user)
        membership = memberships.build_for_user(user)
      end
      membership.access_level = 'member'
      membership.inviter = inviter
      membership.save!
      reload
      membership
    end
  end

  def add_admin!(user)
    unless (membership = memberships.find_by_user_id(user) ||
            membership = membership_requests.find_by_user_id(user))
      membership = memberships.build_for_user(user)
    end
    membership.access_level = 'admin'
    membership.save!
    reload
    membership
  end


  #
  # PERMISSION-CHECKS
  #

  def requested_users_include?(user)
    membership_requests.find_by_user_id(user)
  end

  def has_admin_user?(user)
    return true if admins.include?(user)
    return true if (parent && parent.admins.include?(user))
  end

  #
  # DISCUSSION LISTS
  #

  def all_discussions(user)
    if user
      is_parent_member = user ? user.is_group_member?(self) : false
      Discussion.includes(:group => :memberships)
        .where("(discussions.group_id = ? 
          OR (groups.parent_id = ? AND groups.archived_at IS NULL
            AND (groups.viewable_by = 'everyone'
              OR (groups.viewable_by = 'members' AND memberships.user_id = ?)
              OR (groups.viewable_by = 'parent_group_members' AND ?)
              )
            )
          )", id, id, user.id, is_parent_member)
    else
      Discussion.includes(:group)
        .where("(discussions.group_id = ? OR (groups.parent_id = ? AND groups.archived_at IS NULL
          AND groups.viewable_by = 'everyone'))", id, id)
    end
  end

  def discussions_with_current_motion(user)
    if all_discussions(user)
      all_discussions(user).includes(:motions).where('motions.phase = ?', "voting")
    else
      []
    end
  end

  def discussions_with_current_motion_not_voted_on(user)
    if all_discussions(user)
      (all_discussions(user).includes(:motions).where('motions.phase = ?', "voting") -  discussions_with_current_motion_voted_on(user))
    else
      []
    end
  end

  def discussions_with_current_motion_voted_on(user)
    if all_discussions(user)
      all_discussions(user).includes(:motions => :votes).where('motions.phase = ? AND votes.user_id = ?', "voting", user.id).order("last_comment_at DESC")
    else
      []
    end
  end

  def discussions_sorted(user= nil)
    if user && user.group_membership(self)
      user.discussions
        .where("discussions.id NOT IN (SELECT discussion_id FROM motions WHERE phase = 'voting')")
        .includes(:group)
        .where('discussions.group_id = ? OR (groups.parent_id = ? AND groups.archived_at IS NULL)', id, id)
        .order("last_comment_at DESC")
    else
      all_discussions(user= nil)
        .where("discussions.id NOT IN (SELECT discussion_id FROM motions WHERE phase = 'voting')")
        .order("last_comment_at DESC")
    end
  end


  #
  # PRIVATE METHODS
  #

  private

  def set_defaults
    self.viewable_by ||= :everyone if parent.nil?
    self.viewable_by ||= :parent_group_members unless parent.nil?
    self.members_invitable_by ||= :members
  end

  def add_creator_as_admin
    add_admin! creator
  end

  def create_welcome_loomio
    unless parent
      comment_str = "Hey folks, I've been thinking it's time for a holiday. I know some people might be worried about our carbon footprint, but I have a serious craving for space-cheese!

What does everyone think?"
      description_str = "Welcome to Loomio, a new tool for group decision-making.

By engaging on a topic, discussing various perspectives and information, and addressing any concerns that arise, your group can put their heads together to find the best way forward.

You can use this example discussion to play around with the features of the tool.

To get the ball rolling, Loomio Helper Bot thinks it would be a great idea for your group to take a holiday together. The pie graph on the right shows how your group feels about the proposal. You can have your say by clicking on one of the decision buttons underneath. "
      motion_str = "Loomio Helper Bot is really keen for your group to invest in a trip to the moon. Apparently the space-cheese is delicious. But the implications for your carbon footprint are worrying.

Is it a good idea? Loomio Helper Bot wants to know what you think!

If you're clear about your position, click one of the icons below (hover over the decision buttons for a description of what each one means).

You'll be prompted to make a short statement about the reason for your decision. This makes it easy to see a summary of what everyone thinks and why. You can change your mind and edit your decision freely until the proposal closes."

app/controllers/groups_controller.rb
class GroupsController < GroupBaseController
  load_and_authorize_resource except: :show
  before_filter :authenticate_user!, except: :show
  before_filter :check_group_read_permissions, :only => :show

  def create
    @group = Group.new(params[:group])
    @group.creator = current_user
    if @group.save
      @group.add_admin! current_user
      flash[:success] = "Group created successfully."
      redirect_to @group
    else
      redirect_to :back
    end
  end

  def show
    @group = GroupDecorator.new(Group.find(params[:id]))
    @subgroups = @group.subgroups.accessible_by(current_ability, :show)
    @motions_not_voted = []
    if current_user
      @discussions_with_current_motion_voted_on = @group.discussions_with_current_motion_voted_on(current_user)
      @discussions_with_current_motion_not_voted_on = @group.discussions_with_current_motion_not_voted_on(current_user)
      @discussion = Discussion.new(group_id: @group.id)
    else
      @discussions_with_current_motion_voted_on = @group.discussions_with_current_motion(current_user)
      @discussions_with_current_motion_not_voted_on = []
    end
  end

  def edit
    @group = GroupDecorator.new(Group.find(params[:id]))
  end

  # CUSTOM CONTROLLER ACTIONS

  def archive
    @group = Group.find(params[:id])
    @group.archived_at = Time.current

    @group.subgroups.each do |subgroup|
      subgroup.archived_at = Time.current
      subgroup.save
    end

    if @group.save
      flash[:success] = "Group archived successfully."
      redirect_to dashboard_url
    else
      flash[:error] = "Group could not be archived."
      redirect_to :back
    end
  end

  def add_subgroup
    @parent = Group.find(params[:id])
    @subgroup = Group.new(:parent => @parent)
    @subgroup.members_invitable_by = @parent.members_invitable_by
  end

  def add_members
    params.each_key do |key|
      if key =~ /user_/
        user = User.find(key[5..-1])
        membership = group.add_member!(user, current_user)
        Event.user_added_to_group!(membership)
      end
    end
    flash[:success] = "Members added to group."
    redirect_to group_url(group)
  end

  def request_membership
    if resource.users.include? current_user
      redirect_to group_url(resource)
    else
      @membership = Membership.new
    end
  end

  def new_motion
    @group = GroupDecorator.new Group.find(params[:id])
    @motion = Motion.new
  end

  def create_motion
    @group = Group.find(params[:id])
    @discussion = current_user.authored_discussions.create!(group_id: @group.id,
                  title: params[:motion][:name])
    @motion = @discussion.motions.new(params[:motion])
    @motion.author = current_user
    if @motion.save
      flash[:success] = "Proposal has been created."
      Event.new_motion!(@motion)
      redirect_to @discussion
    else
      flash[:error] = "Proposal could not be created."
      redirect_to :back
    end
  end

  def email_members
    @group = Group.find(params[:id])
    subject = params[:group_email_subject]
    body = params[:group_email_body]
    GroupMailer.deliver_group_email(@group, current_user, subject, body)
    flash[:success] = "Email sent."
    redirect_to :back
  end

  def edit_description
    @group = Group.find(params[:id])
    @description = params[:description]
    @group.description = @description
    @group.save!
  end

  def edit_privacy
    @group = Group.find(params[:id])
    @viewable_by = params[:viewable_by]
    @group.viewable_by = @viewable_by
    @group.save!
  end
  
  private

    def group
      resource
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def display_subgroups_block?(group)
    group.parent.nil? && (group.subgroups.present? || (current_user && group.users_include?(current_user)))
  end

  def css_for_privacy_link(group, link)
    current_privacy_setting = String(group.viewable_by)
    return "icon-ok" if link == current_privacy_setting
  end
end

app/views/groups/_add_members.html.haml
#add-members
  - if can? :add_members, group
    .clearfix
      - if group.parent.blank?
        = icon_button('#', 'Add new member', '/assets/member-18.png', 'group-add-members')
        #invite-group-members.hidden
          = semantic_form_for(User.new, url: user_invitation_path, html: { method: :post }) do |f|
            = devise_error_messages!
            = f.input :group_id, as: :hidden, label: false, input_html: { value: group.id }
            = f.input :email, placeholder: "Email address", label: false
            = f.submit "Invite", class: "btn btn-small", id: 'invite'
            = link_to "Cancel", "#", id: 'cancel-add-members'
        %input#group_id{ type: "hidden", value: group.id }
      - else
        = icon_button("#invite-subgroup-members", 'Add new member', '/assets/member-18.png', 'group-add-members', true)
        #invite-subgroup-members.modal.hidden
          = render 'subgroup_add_members', group: group

app/views/groups/_email_members.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h3= "Email the members in #{group.full_name}"
= form_tag email_members_group_path(group) do
  .modal-body
    .control-group
      = label_tag "group_email_subject", "Subject"
      %span.presence-error-message Please fill in a subject
      = text_field_tag "group_email_subject", nil, :placeholder => "Write a subject", :class => "validate-presence"
    .control-group
      = label_tag "group_email_body", "Message"
      %span.presence-error-message Please fill in a message
      = text_area_tag "group_email_body", nil, :placeholder => "Write a message to the members of #{group.full_name}.", :class => "validate-presence"
  .modal-footer
    = submit_tag "Send email", class: "btn btn-info run-validations"

app/views/groups/_form.html.haml
.row
  .span7
    #group-form
      =form_for(group) do |f|
        .row
          .span5
            .control-group
              = f.label :name, "Group Name",
                {id: "group-name-label", class: "control-label", for: "group-name"}
              #group-name-error.presence-error-message Please fill in a title
              = f.text_field :name, class: "validate-presence inputError limit-250", id: "group-name"
              .character-counter
        .privacy-settings
          #settings-header
            %h3 Settings
          %hr
            - suffix = "group"
            - suffix = "sub-group" unless group.parent.nil?
          .setting-label= "Who can see this #{suffix}?"
          .settings
            .row
              .span3
                =f.radio_button :viewable_by, "everyone"
                =f.label :viewable_by_everyone, "Public"
              .span4
                .explanation.helper-text
                  %p= "- Anyone with a link can see this group"
            .row
              .span3
                =f.radio_button :viewable_by, "members"
                =f.label :viewable_by_members, "Members"
              .span4
                .explanation.helper-text
                  %p= "- Only members of this #{suffix} can see this group"
            - unless group.parent.nil?
              .row
                .span3
                  =f.radio_button :viewable_by, "parent_group_members"
                  =f.label :viewable_by_parent_group_members, "Parent group members"
                .span4
                  .explanation.helper-text
                    %p= "- Only members of this sub-group and the parent group can see this sub-group"
          %hr
          .setting-label= "Who can invite members to this #{suffix}?"
          .settings
            .row
              .span3
                =f.radio_button :members_invitable_by, "members"
                =f.label :members_invitable_by_everyone, "All group members"
            .row
              .span3
                =f.radio_button :members_invitable_by, "admins"
                =f.label :members_invitable_by_admins, "Admins only"
          %hr
        =f.hidden_field :parent_id, :value => parent.id unless parent.nil?

        .settings
          .notification-settings
            = f.check_box :email_new_motion # TODO: check this by default
            = f.label :email_new_motion,
              "Email group members when a new motion is created in this group", class: "checkbox-label"
        = f.submit submit_text, class: "btn btn-info run-validations", id: "update-group", :data => {:disable_with => "Updating group"}

app/views/groups/_members.html.haml
- unless group.hide_members && (cannot? :edit, group)
  .sub-panel
    .membership-count.label
      = group.memberships.count
    %h3 Members
    = render 'add_members', group: group
    %ul#users-list
      = render :partial => 'membership',
        :collection => group.memberships,
        :locals => { group: group }

app/views/groups/_membership.html.haml
%li{:id => membership.user_id}
  .clearfix
    .small-user-avatar.avatar-canvas
      - if membership.user.avatar_url
        = image_tag membership.user.avatar_url(:small)
      - else
        %span.small-user-initials.initials-decoration= membership.user.avatar_initials
    - member = User.find(membership.user_id)
    .user-name
      - name_length = (member.is_group_admin?(group) or (can? :edit, group and current_user.is_group_admin?(group))) ? 18 : 35
      %span.membership-user-name
        = link_to truncate(membership.user_name_or_email, :length => name_length, :omission => '...'), "#", "title" => membership.user_name_or_email, "data-content" => "#{render 'users/name_popover', user: membership.user, group: group }", class: 'user-name-with-popover'
    .admin-controls
      - if (can? :edit, group and current_user.is_group_admin?(group))
        =link_to "×", membership, method: :delete, class: 'close',
          :data => { :confirm => "Are you sure you wish to remove #{membership.user_email} from the group?" }
        - if member.is_group_admin?(group)
          =link_to "Remove admin", remove_admin_membership_path(membership), method: :post
        - else
          =link_to "Make admin", make_admin_membership_path(membership), method: :post
      - else
        - if member.is_group_admin?(group)
          = "Group Admin"

app/views/groups/_membership_request.html.haml
%li
  .clearfix
    .membership-user-name= truncate(membership_request.user_name, :length => 29, :omission => '...')
    .admin-controls
      =link_to "×", ignore_request_for_membership_path(membership_request), :method => :post, class: 'close',
          :data => {:confirm => "Are you sure you want to ignore the member request from #{membership_request.user_email}?" }
      =link_to 'Approve', approve_request_for_membership_path(membership_request), :method => :post,
        :data => { :confirm => "Are you sure you want to add #{membership_request.user_email} to the group?" }

app/views/groups/_membership_requests.html.haml
- if group.membership_requests.present? && (can? :add_members, group)
  .sub-panel#user-requests
    %h3 Membership requests
    %ul#request-list
      =render :partial => 'membership_request', :collection => group.membership_requests

app/views/groups/_subgroup_add_members.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h3= "Select members to add to #{group.name}"
= form_tag add_members_group_path do
  .modal-body
    - group.parent.users_sorted.each do |member|
      - unless member == current_user
        .invite-member-checkbox-container
          - is_member = false
          - is_member = true if group.users_include?(member)
          = check_box_tag "user_#{member.id}", 1, is_member, disabled: is_member
          = label_tag "user_#{member.id}", member.name
  .modal-footer
    = submit_tag "Invite members", class: "btn btn-small btn-info"

app/views/groups/_title.html.haml
.page-container
  .group-title.clearfix
    - if group
      %h1
        .home-title= link_to "Home", "/"
        = content_tag :span, "\u25B6", class: 'name-separator'
        = group.fancy_link
      .dropdown.privacy-dropdown
        %a.dropdown-toggle{ :href => "#", :id => 'privacy', 'data-toggle' => 'dropdown',  "data-title" => "Privacy: '"+group.viewable_by.to_s+"' can see this group." }
          = image_tag("privicon_"+group.viewable_by.to_s+".png", alt: group.viewable_by.to_s, :id => 'privacy-image')
        - if can? :edit, group
          = render 'groups/privacy_settings', :group => group
      - if params[:controller] == 'groups' && params[:action] == 'show'
        - can_edit = can? :edit, group
        - can_leave = group.users_include? current_user
        - can_archive = can? :edit, group
        - can_email = can? :email_members, group
        - if can_edit || can_leave
          .dropdown.btn-group.group-options
            %a.btn.btn-grey.btn-app.dropdown-toggle{ :href => "#", 'data-toggle' => 'dropdown' }
              %i.icon-cog
              Options
              = image_tag("dropdown.png", title:'Options', alt:'Options', class: "options-dropdown-icon")
            %ul.dropdown-menu.pull-right
              - if can_email
                %li= link_to "Email group members", "#email-members-modal", "data-toggle" => "modal"
                %hr
              - if can_edit
                %li= link_to "Edit group settings", edit_group_path(group)
              - if can_leave
                - membership = current_user.group_membership(group)
                %li= link_to "Leave group", membership, method: :delete, :data => { confirm: "Are you sure you wish to leave #{group.name}?" }
              - if can_archive
                %li= link_to "De-activate group", archive_group_path(group), method: :post, :data => { confirm: "Wait!!! Are you sure you want to de-activate #{group.name}? \n\n You will no longer be able to view the group. However, if you wish to get the group back you can ask us to reactivate it for you by sending an email to contact@loom.io." }
        - if can_email
          #email-members-modal.modal.hidden
            = render "groups/email_members", :group => group
    - else
      %h1
        .home-title= "Home"

app/views/groups/edit.html.haml
- set_title @group.name, "Edit Group"
= render '/groups/title', group: @group
= render 'form', group: @group, parent: @parent,
  submit_text: "Update group", :data => { :disable_with => "Updating group" }

app/views/groups/edit_privacy.js.erb
$("#privacy-image").attr('src', "/assets/privicon_<%= @group.viewable_by.to_s %>.png")

app/views/groups/new.html.haml
- set_title "", "New Group"
%h1 New Group
= render 'form', group: @group, parent: @parent,
  submit_text: "Create group", :data => { :disable_with => "Creating group" }

app/views/groups/private_or_not_found.html.haml
#private-message
  %br
  %h2 Group not found.
  %br
  %h2 This group might be private. If someone gave you this link, they may need to invite you to one of their groups so that you can see this page.

app/views/groups/show.html.haml
- set_title @group.name, "", @group.parent
- if user_signed_in? && @group.parent.nil? && (not current_user.has_read_group_notice?)
  - message = "This is the Group page for \"#{@group.full_name}\". \n\n Here you can see this group’s discussions, "
  - message += "a description of what the group is for, "
  - message += "You can start a discussion on a new topic by clicking on the ‘Start a discussion’ button.\n\n"
  =render '/application/helper_info', message: message, path: dismiss_group_notice_for_user_path

-#= render '/application/loomio_process_flow'
= render '/groups/title', group: @group
.clearfix
  =render 'application/helper_bot'
  - if can? :create, @discussion
    = icon_button('#new-discussion', 'Start a discussion', '/assets/topic-18.png', 'start-new-discussion', true)
.row.main-content
  %section.span8
    %ul.selector-list.bordered
      #all-discussions-loading
        %li.selector-item.loading Loading...
      #discussions-with-motions
        - @discussions_with_current_motion_not_voted_on.each do |discussion|
          %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: @group
        - @discussions_with_current_motion_voted_on.each do |discussion|
          %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: @group
        .discussion-with-motion-divider.hidden
      - if @group.discussions.count == 0
        %li.empty-list-message This group does not have any discussions yet.
      - else
        #group-discussions.hidden
          %div{ class: "group_#{@group.id}" }

  %section.span4
    =render 'request_membership', group: @group
    .sub-panel#group-description-panel
      %h3= "Group description"
      =render '/application/description', model: @group, model_name: "group"
    =render 'subgroups', subgroups: @subgroups, group: @group if display_subgroups_block?(@group)
    =render '/application/see_closed_motions'
    =render 'membership_requests', group: @group
    =render 'members', group: @group
  =render '/application/closed_motions', user: nil, group: @group

- if can? :create, @discussion
  =render '/discussions/new', discussion: @discussion, user_groups: nil